# Generated by Django 4.2.4 on 2023-08-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('item_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_image', models.FileField(upload_to='items/')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='store.categories')),
            ],
        ),
    ]
