# Generated by Django 4.2.4 on 2023-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_fooditem_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
