# Generated by Django 4.2.4 on 2023-08-25 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_rating', models.PositiveIntegerField(choices=[(1, 'Not Satisfied'), (2, 'Somewhat Satisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')])),
                ('product_quality_comment', models.TextField(blank=True)),
                ('delivery_experience_comment', models.TextField(blank=True)),
                ('customer_service_comment', models.TextField(blank=True)),
                ('ease_of_ordering_comment', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('recommend_rating', models.PositiveIntegerField(choices=[(1, 'Not Likely'), (2, 'Somewhat Likely'), (3, 'Neutral'), (4, 'Likely'), (5, 'Very Likely')])),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
