# Generated by Django 4.2.4 on 2023-08-25 08:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, null=True, region='NG'),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region='NG'),
        ),
    ]
