# Generated by Django 4.2.4 on 2023-08-25 08:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_address_orders_contact_1_orders_contact_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='contact_2',
        ),
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=15, region='NG'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=90),
        ),
    ]
