# Generated by Django 4.2.4 on 2023-08-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_contact_1_remove_orders_contact_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order Processed', 'verbose_name_plural': 'Orders Processed'},
        ),
    ]
